/*
CHIMALTENANGO, 09 DE FEBRERO DE 2019
PROGRAMADOR: LUIS FERNANDO CUMEZ QUINA

	DESCRIPCION DEL PROGRAMA :
	ES UN PROGRAMA EJEMPLO QUE MUESTRA LOS DATOS PERSONALES
	DE ALGUIEN.

*/

#include "pch.h"	//LIBRERIA CONSTANTE
#include <iostream> //LIBRERIA PARA LA ENTRADA Y SALIDA DE DATOS

using namespace std; //PERMITE EL USO DE COUT Y CIN

int main()
{
	cout << "NOMBRES: LUIS FERNANDO" << endl;	     //MUESTRA EL NOMBRE DE LA PERSONA EN PANTALLA
	cout << "APELLIDOS: CUMEZ QUINA" << endl;	             //MUESTRA LOS APELLIDOS DE LA PERSONA EN PANTALLA
	cout << "EDAD: 18" << endl;	                     //MUESTRA LOS AÑOS DE LA PERSONA EN PANTALLA
	cout << "DIRECCION: 0 AVE. B 4-110 ZONA 4" << endl;    //MUESTRA LA DIRECCION DE LA PERSONA EN PANTALLA
	cout << "TELEFONO: 30460228" << endl;	             //MUESTRA EL NUMERO DE TELEFONO DE LA PERSONA EN PANTALLA
	cout << "GENERO(SEXO): M" << endl;	             //MUESTRA EL GENERO DE LA PERSONA EN PANTALLA
	cout << "PAGO DE COLEGIATURA: 500 QUETZALES" << endl;  //MUESTRA LA COLEGIATURA DE LA PERSONA EN PANTALLA

	system("pause");
	return 0;
}
